// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa6QPTdUYAo-8QtNjspXPHXchmrV3GcXU',
    appId: '1:198668184911:web:821bda8729469d7d17e93a',
    messagingSenderId: '198668184911',
    projectId: 'explorex-e052d',
    authDomain: 'explorex-e052d.firebaseapp.com',
    storageBucket: 'explorex-e052d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCakaNu9PZYqAWGZ-k7vC4zk3_FHlZPYDQ',
    appId: '1:198668184911:android:22e25a9a0156d14517e93a',
    messagingSenderId: '198668184911',
    projectId: 'explorex-e052d',
    storageBucket: 'explorex-e052d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLarQmTEvEUrhAdxFW87IHHgAPgF037qU',
    appId: '1:198668184911:ios:5b078dffae5ddb2917e93a',
    messagingSenderId: '198668184911',
    projectId: 'explorex-e052d',
    storageBucket: 'explorex-e052d.firebasestorage.app',
    iosBundleId: 'com.example.explorex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLarQmTEvEUrhAdxFW87IHHgAPgF037qU',
    appId: '1:198668184911:ios:5b078dffae5ddb2917e93a',
    messagingSenderId: '198668184911',
    projectId: 'explorex-e052d',
    storageBucket: 'explorex-e052d.firebasestorage.app',
    iosBundleId: 'com.example.explorex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa6QPTdUYAo-8QtNjspXPHXchmrV3GcXU',
    appId: '1:198668184911:web:40d2af49e913a25817e93a',
    messagingSenderId: '198668184911',
    projectId: 'explorex-e052d',
    authDomain: 'explorex-e052d.firebaseapp.com',
    storageBucket: 'explorex-e052d.firebasestorage.app',
  );
}
